### ISSUE TITLE
Source code for pre-built libraries

### ISSUE THREAD

**Issue by nimish** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#11]
Is the source for libraries in `EPII_CM55M_APP_S/prebuilt_libs/gnu` available or planned to be available?

After some analysis, they are just wrappers around setting registers for peripherals including ones that are already open source like synopsys designware and cadence stuff. Beyond proprietary peripherals and registers it's not clear why the source isn't included since the information is in the headers anyway.

**Comment by kris-himax** [comment]
Hi @nimish,

We appreciate your inquiry regarding the source availability for the libraries in EPII_CM55M_APP_S/prebuilt_libs/gnu. At this time, we do not have plans to release the source code for the drivers.

Thanks,
Kris
