### ISSUE TITLE
Can the Grove Vision AI V2 be programmed on the Arduino IDE

### ISSUE THREAD

**Issue by hpssjellis** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#14]
**Can the Grove Vision AI V2 be programmed on the Arduino IDE**

I just want to use the SD card, but assume I have to use a different platform.

**Comment by stevehuang82** [comment]
Hi @hpssjellis ,

    The following link describes the communication between Grove Vision AI V2 and XIAO(arduino).  Hope his helps.

https://wiki.seeedstudio.com/grove_vision_ai_v2_at/

**Comment by hpssjellis** [comment]
Thanks @stevehuang82 I see that area has some information about the SD card and saving images   

https://wiki.seeedstudio.com/grove_vision_ai_v2_at/#example-3-saving-jpeg-images-to-sd-card

We can close this.
