### ISSUE TITLE
Build failed when using APP_TYPE = tflm_yolo8_od

### ISSUE THREAD

**Issue by JakeSays** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#17]
I am trying to build the firmware using the `tflm_yolo8_od` app type. The build fails with this error:

> /trustzone/tz_cfg/trustzone_cfg.h:16:10: fatal error: CM55M_TrustZone_FW_mem.h: No such file or directory
>   16 | #include "CM55M_TrustZone_FW_mem.h"

The build succeeds with `APP_TYPE = allon_sensor_tflm`. What is different between the two app types?

**Comment by stevehuang82** [comment]
Hi @JakeSays 

The APP_TYPE="tflm_yolo8_od" is a typo. It should be "tflm_yolov8_od". Please try again. Thanks.

**Comment by JakeSays** [comment]
@stevehuang82 ah that fixed it:) Thanks!
