### ISSUE TITLE
Memory map

### ISSUE THREAD

**Issue by TCHeish** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#19]
Is there any documentation about memory map like [this](https://review.mlplatform.org/plugins/gitiles/ml/ethos-u/ml-embedded-evaluation-kit/+/refs/heads/main/docs/sections/appendix.md#appendix). Thanks.

**Comment by stevehuang82** [comment]
Hi @TCHeish ,

You can find the memory map here. https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/blob/main/FAQ.md

**Comment by TCHeish** [comment]
Hi @stevehuang82 
Thanks. How about FLASH? Is it the sec_6 mention [here](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/blob/342824ab1772705fba5977ee16d95fc193f4bf0a/we2_image_gen_local/common/sec_mem/sec_mem_layout_one_sonly_bin.json#L27) ?

**Comment by stevehuang82** [comment]
Hi @TCHeish 
Yes, the starting address of Flash in XIP mode is 0x3A000000.
