### ISSUE TITLE
What needs to be done to use an RPI camera?

### ISSUE THREAD

**Issue by skol101** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#2]
We've got RPI HQ camera to just in the project, but looks like there's no support for in Ai V2. So, do we have to add the driver to firmware and install it?

**Comment by kris-himax** [comment]
@skol101 ,
Hi, we are working on it. coming soon.

Thanks,
Kris

**Comment by skol101** [comment]
Does this require buying a new AI V2 module ? 
Or it works on modules produced before 2024/02/20?

**Comment by kris-himax** [comment]
It works on modules produced before 2024/02/20.
