### ISSUE TITLE
App tflm_fd_fm, use GPIO

### ISSUE THREAD

**Issue by hatrinh-sj** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#21]
Hi Kris,

My requirement is simple: if a face is detected, turn on a specific GPIO pin. Is it possible to use GPIO on Vision AI V2? I use serial only for debugging. I don't need face mesh or landmark.

**Comment by stevehuang82** [comment]
Hi @hatrinh-sj,

You can configure PA0(D0) as a GPIO function using the following method:

#include "hx_drv_gpio.h"

// Configure PA0(D0) as GPIO0
hx_drv_gpio_set_output(AON_GPIO0, GPIO_OUT_LOW);
hx_drv_scu_set_PA0_pinmux(SCU_PA0_PINMUX_AON_GPIO0_2, 1);

// set GPIO0 output high
hx_drv_gpio_set_out_value(AON_GPIO0, GPIO_OUT_HIGH);

// set GPIO0 output low
hx_drv_gpio_set_out_value(AON_GPIO0, GPIO_OUT_LOW);

![grove_ai_v2_pinout](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/assets/48747994/740f496e-5885-416b-9f53-dfff0c8fba3c)

**Comment by hatrinh-sj** [comment]
Thank you. I guess I must put the command to flip the pin in function cv_fd_fm_run in cvapp_fd_fm.cpp. Is it correct?

```
    if (alg_result->num_tracked_human_targets == 0)
	{
    	//need to wait jpeg transfer done
        ...
        hx_drv_gpio_set_out_value(AON_GPIO0, GPIO_OUT_LOW);

	}
    else {
       hx_drv_gpio_set_out_value(AON_GPIO0, GPIO_OUT_HIGH);
       ...

    }
```

**Comment by stevehuang82** [comment]
Yes, it is.
