### ISSUE TITLE
Apple Silicon ARM version of we2_local_image_gen

### ISSUE THREAD

**Issue by stantonious** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#22]
The current version of we2_local_image_gen does not run on MacBook Pro M1.  We've tried running with Rosetta2, no luck.

**Comment by kris-himax** [comment]
Hi @stantonious,

 The we2_local_image_gen can run on MacBook Pro now. You can reference the [Build the firmware at MacOS environment](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2?tab=readme-ov-file#build-the-firmware-at-macos-environment) part of Readme.


Thanks,
Kris

**Comment by stantonious** [comment]
Thanks @kris-himax.  We'll check it out today.
