### ISSUE TITLE
What are the Grove Vision AI V2 connection pins

### ISSUE THREAD

**Issue by hpssjellis** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#3]
@kris-himax 

What are the active pins between the XIAO and the Grove Vision AI V2?

I need to connect a servo and big motor driver to the xiao while it communicates with the Grove Vision AI V2.

My Guess is on the XIAO connect 3V3, GND, SDA (D4), SCL(D5) to the equivalent locations on the Grove. Do you have any better suggestions?

Note: I am having success compiling pins: D0(digital-output) , D1 (digital-output), D2 (servo-output) and D6 (pwm-output). Curious why D3 does not work for with PWM-output.

![image](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/assets/5605614/848ffaf7-38a5-45ff-941c-c42e05680964)

**Comment by flagyan** [comment]
Hi @hpssjellis,

In the [sch](https://files.seeedstudio.com/wiki/grove-vision-ai-v2/Grove_Vision_AI_Module_V2_Circuit_Diagram.pdf), the pin definition is as below, is this what you need?
![image](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/assets/1866369/adb13d37-acd4-493e-9b94-34f973edb77b)

**Comment by stevehuang82** [comment]
Hi @hpssjellis,

Thanks to @flagyan for replying to the Grove Vision AI V2 pin definition. Grove Vision AI V2 can communicate with XIAO through UART/I2C/SPI/GPIO according to your needs. Regarding XIAO's question "Why D3 cannot be used for PWM output", you can ask Seeed Studio.

**Comment by hpssjellis** [comment]
@flagyan and @stevehuang82 yeh I guess the Grove pins are just a mirror image of the XIAO, that makes sense. My main question was more about the minimum pins to communicate between the two boards and I basically have it working just using I2C, 3v3 and GND, so 4 pins.

The reason I asked about D3 is that the boards were both plugged together when I had the compile issue so I was wondering if the Grove Vision AI V2 was using that pin for something.  I should probably test it again now that I have separated the two boards.

So far things are going good with my RoboCar. I still have several more steps to go.


![image](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/assets/5605614/4b6cc73e-7112-4402-8452-b65330749fd6)

**Comment by stevehuang82** [comment]
Hi @hpssjellis ,

    Grove Vision AI V2 pin D3(RST) is connected to the WE2 chip reset pin. Users can use XIAO pin D3 (GPIO4) to reset Grove Vision AI V2 (WE2 chip).
      You can try toggling Grove Vision AI V2 pin D3(RST) (set low and high) and you will see Grove Vision AI V2 reset.

**Comment by stevehuang82** [comment]
Hi @hpssjellis ,
Grove Vision AI V2 pin D3(RST) is connected to the WE2 chip reset pin. Users can use XIAO pin D3 (GPIO4) to reset Grove Vision AI V2 (WE2 chip).
You can try toggling Grove Vision AI V2 pin D3(RST) (set low and high) and you will see Grove Vision AI V2 reset.

**Comment by hpssjellis** [comment]
> Hi @hpssjellis , Grove Vision AI V2 pin D3(RST) is connected to the WE2 chip reset pin. Users can use XIAO pin D3 (GPIO4) to reset Grove Vision AI V2 (WE2 chip). You can try toggling Grove Vision AI V2 pin D3(RST) (set low and high) and you will see Grove Vision AI V2 reset.

Thanks, that explains the issue I had. I can close this.
