### ISSUE TITLE
how to download the firmware image larger than 1MB

### ISSUE THREAD

**Issue by flagyan** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#30]
Hi,

Is there a method to download firmware image larger than 1MB? I have built my library in the firmware and got a 1.5MB .img file. Thanks in advance.

**Comment by stevehuang82** [comment]
Hi @flagyan,

Firmware image size cannot be larger than 1MB. Does your code include model files? If so, you can put the model file into flash memory.

**Comment by flagyan** [comment]
Hi @stevehuang82,

I have a very big library to implement complex functions and so result in a 1.5M image file. Where is the limitation of 1MB from? Is  it from the download function? Then can I use the debugger to flash it directly? Thanks.

**Comment by stevehuang82** [comment]
Yes, the limitation is from the download function. I think you can use the debugger to flash it directly. I will confirm that later.

**Comment by flagyan** [comment]
Hi @stevehuang82 ,

I am setting up the debug environment with jlink and get the 'Unspecified error' as #28,  do we need any extra setting besides
[https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/blob/main/swd_debugging/README.md](swd_debugging/README.md)? for example, enable the SWD in the image, I see that in the [https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/blob/main/EPII_CM55M_APP_S/app/scenario_app/allon_sensor_tflm_freertos/allon_sensor_tflm.c](allon_sensor_tflm.c), there is code to enable the swd but it is commented out. Thanks a lot.

**Comment by flagyan** [comment]
Hi @stevehuang82,

I can download the image with a cmsis-dap debugger now. Thanks a lot.
