### ISSUE TITLE
Getting Crop Image Instead of Full Image

### ISSUE THREAD

**Issue by saricaBugrahan** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#5]
Hi,
I am trying to apply the cropping operation according to the coordinates which comes from cvapp_yolo8n_ob.cpp file. I have found where the cropping macros are defined. However, I did not understand how to combine the it together. Are there any suggestions that you can give me?

Thank you,

**Comment by kris-himax** [comment]
Hi @saricaBugrahan ,

You can use the [hx_lib_image_copy_helium](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/blob/main/EPII_CM55M_APP_S/library/img_proc/img_proc_helium.h#L89C6-L89C35) to crop image.

the input parameters are following.
```
/**
 * @brief Extract a region from a given image. using Helium optimize.
 * 
 * @param[in] im input image address
 * @param[out] cropped Cropped image address
 * @param[in] input_w  the weight of input image
 * @param[in] input_h  the hight of input image
 * @param[in] input_c the channels of input image
 * @param[in] dx The x-coordinate, in logical units of the crop offset.
 * @param[in] dy The y-coordinate, in logical units of the crop offset.
 * @param[in] w The width of the crop.
 * @param[in] h The height of the crop.
 */
void hx_lib_image_copy_helium(uint8_t* im, uint8_t* cropped, int input_w, int input_h, int input_c, int dx, int dy, int w, int h);

```
