### ISSUE TITLE
Firmware Build

### ISSUE THREAD

**Issue by saricaBugrahan** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#6]
Hi,

I am able to build and upload the firmware through the ReadME file. However, after uploading the firmware I cannot communicate through MCU or SeedCraftAI tool. Its not displaying any image. If I upload it through SeedCraft predefined models or prebuild image in the repository I can able to communicate both of them. What should be the issue? Is there anything that I need to do further than ReadME file? Thank you.

**Comment by kris-himax** [comment]
Hi @saricaBugrahan ,
If you want to send the image and meta data out from MCU by uart and show on web UI, you should reference the scenario_app which is [tflm_fd_fm](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/tree/main/EPII_CM55M_APP_S/app/scenario_app/tflm_fd_fm) , [tflm_yolov8_od](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/tree/main/EPII_CM55M_APP_S/app/scenario_app/tflm_yolov8_od) or [yolov8_pose](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/tree/main/EPII_CM55M_APP_S/app/scenario_app/tflm_yolov8_pose). And reference the [send image part of readme](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2?tab=readme-ov-file#send-image-and-meta-data-by-uart) to download [Himax AI web UI](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/releases/download/v1.1/Himax_AI_web_toolkit.zip)

**Comment by saricaBugrahan** [comment]
Hi @kris-himax,
I tried the tflm_yolov8_od scenario_app. Firmware build was a success. However, whenever I upload the output.img file to the board, board always rebooting because of the unsufficent memory. The output of the UART output is below. I will try the other scenario_app's and let you know.
![Screenshot from 2024-03-14 09-07-42](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/assets/98035249/d03a5807-c20f-42ae-9919-b10554fe77fb)

**Comment by kris-himax** [comment]
Hi @saricaBugrahan,
you should disconnect the uart at your command line, so that it can connect to Web GUI correct.

**Comment by saricaBugrahan** [comment]
Hi @kris-himax,
I enabled the UART Debug Output in tflm_yolov8_od.cpp file. Shouldn't I need to see the debug xprintf lines if the board succesfully flashed?. I will try it right now with the Web GUI and let you know.

**Comment by saricaBugrahan** [comment]
EDIT: I also tested with the Web GUI, after the initial image is loaded there is no output coming from the board except the FPS. The image is not refreshing itself and stay stucked. The screenshot is below.
![Screenshot from 2024-03-14 10-30-05](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/assets/98035249/9ebb1a1f-df94-429a-9391-2c980ca5d85a)

**Comment by kris-himax** [comment]
Did you try other example?

**Comment by saricaBugrahan** [comment]
Yes. Its the same issue, the last thing I did not try is tflm_yolov8_pose. I will try it now
