### ISSUE TITLE
arm64 linux version of ./we2_local_image_gen

### ISSUE THREAD

**Issue by Gostas** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#72]
Hi there, I am using a Raspberry Pi 5 and currently getting the error `bash: ./we2_local_image_gen: cannot execute binary file: Exec format error` when trying to create the firmware image.

Could you please add a linux arm64 version of this binary?

Thanks

**Comment by stevehuang82** [comment]
Hi @Gostas,

Sorry, we currently have no plans to support the linux arm64 version.

**Comment by Gostas** [comment]
Oh okay. I saw that you added support for mac on arm fairly recently. Would it be more difficult to add an executable for linux arm64?

Alternatively, is there some way I can make the firmware image with the provided binary on my Raspberry Pi?

**Comment by stevehuang82** [comment]
We do not have a Raspberry Pi environment to build the image generation tool library.
Maybe you could use a Windows, Ubuntu or Mac environment to build the code and generate the firmware image, it should be more efficient.
