### ISSUE TITLE
wrong declaration in allon_sensor_tflm.h

### ISSUE THREAD

**Issue by acutetech** [HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2#8]
I downloaded your SDK yesterday. I see that by default the application is allon_sensor_tflm_freertos.

This did not build because the .h file declares int rtos_app(void); which does not exist. When I changed this to int app_main(void); it builds.

**Comment by kris-himax** [comment]
Thank you for your reminder. We update it.
